import { homedir } from 'node:os';
import path from 'node:path';
import type { SettingDefinition, SettingGroup, SideEffect } from '@gamecrafter/contracts';

export interface BuiltinSettings {
  groups: SettingGroup[];
  definitions: SettingDefinition[];
}

export function createBuiltinSettings(): BuiltinSettings {
  const groups: SettingGroup[] = [
    {
      id: 'general',
      title: 'General & background behaviour',
      description: 'General settings for the Control Room and background service.',
      order: 0,
    },
    {
      id: 'projects',
      title: 'Projects, genres & modules',
      description: 'Project creation and organization defaults.',
      order: 1,
    },
    {
      id: 'agents',
      title: 'Agents, swarms & skills',
      description: 'Agent delegation and skill behavior.',
      order: 2,
    },
    {
      id: 'models',
      title: 'Model providers & routing',
      description: 'Model selection and task budgets.',
      order: 3,
    },
    {
      id: 'connections',
      title: 'Engine, asset & tool connections',
      description: 'Connections to game engines, asset services, and tools.',
      order: 4,
    },
    {
      id: 'access',
      title: 'Access & security',
      description: 'Access controls and security policies.',
      order: 5,
    },
    {
      id: 'board',
      title: 'Discussion board',
      description:
        'Discussion board behavior and maintenance routed through the board-maintainer model pool.',
      order: 6,
    },
    {
      id: 'plugins',
      title: 'Plugins & updates',
      description: 'Platform plugin installation and update behavior.',
      order: 7,
    },
    {
      id: 'storage',
      title: 'Storage, search & backup',
      description: 'Search indexes, backup, and storage behavior.',
      order: 8,
    },
    {
      id: 'logs',
      title: 'Logs & audit',
      description: 'Logging and audit retention.',
      order: 9,
    },
    {
      id: 'engine',
      title: 'Engine connectors',
      description: 'Engine detection, capability reporting, and operation behavior.',
      order: 10,
    },
    {
      id: 'knowledge',
      title: 'Knowledge & search',
      description: 'Canon records, indexing, semantic search, and retrieval behavior.',
      order: 11,
    },
    {
      id: 'assets',
      title: 'Assets',
      description: 'External generation, asset imports, previews, and cache behavior.',
      order: 12,
    },
    {
      id: 'backup',
      title: 'Backups',
      description: 'Encrypted Project and profile backup, verification, restore, and retention.',
      order: 13,
    },
    {
      id: 'dcc',
      title: 'DCC tools',
      description: 'DCC installation detection, scripted operations, and preview rendering.',
      order: 14,
    },
    {
      id: 'coordination',
      title: 'Coordination',
      description: 'Change impact, agent execution, resource locks, and worktree integration.',
      order: 15,
    },
    {
      id: 'updates',
      title: 'Updates',
      description: 'Release checks, downloads, and user-controlled update installation.',
      order: 16,
    },
  ];
  const definitions: SettingDefinition[] = [
    setting(
      'window.closeBehavior',
      'Window close behavior',
      'Choose whether closing the window leaves work running or stops after checkpointing.',
      'general',
      { type: 'string', enum: ['continue', 'stop-and-checkpoint'] },
      'continue',
      ['platform'],
    ),
    setting(
      'projects.defaultParentDirectory',
      'Default Project parent directory',
      'Default directory used when creating Projects.',
      'projects',
      { type: 'string' },
      path.join(homedir(), 'GameCrafterProjects'),
      ['platform'],
    ),
    setting(
      'agents.maxSpawnDepth',
      'Maximum agent spawn depth',
      'Maximum number of nested agent delegation levels.',
      'agents',
      { type: 'integer', minimum: 1, maximum: 16 },
      4,
      ['platform', 'project'],
    ),
    setting(
      'agents.maxConcurrentPerProject',
      'Maximum concurrent agents per Project',
      'Maximum number of agents that can work concurrently on one Project.',
      'agents',
      { type: 'integer', minimum: 1, maximum: 64 },
      8,
      ['platform', 'project'],
    ),
    setting(
      'access.mode',
      'Access mode',
      'Controls how tool operations are authorized.',
      'access',
      { type: 'string', enum: ['full', 'restricted', 'ask-always'] },
      'ask-always',
      ['platform', 'project', 'session'],
    ),
    setting(
      'access.restricted.allowedSideEffects',
      'Allowed restricted-mode side effects',
      'Side-effect categories permitted without an explicit tool allowlist.',
      'access',
      {
        type: 'array',
        items: {
          type: 'string',
          enum: [
            'none',
            'internal-write',
            'workspace-write',
            'external-write',
            'paid',
            'destructive',
          ],
        },
        uniqueItems: true,
      },
      ['none', 'internal-write', 'workspace-write'] as SideEffect[],
      ['platform', 'project'],
    ),
    setting(
      'access.restricted.allowedTools',
      'Allowed restricted-mode tools',
      'Tool ID globs permitted while access is restricted.',
      'access',
      { type: 'array', items: { type: 'string' }, uniqueItems: true },
      [],
      ['platform', 'project'],
    ),
    setting(
      'access.askAlways.approvalTimeoutMinutes',
      'Approval timeout (minutes)',
      'How long approval requests remain pending.',
      'access',
      { type: 'integer', minimum: 1 },
      30,
      ['platform', 'project', 'session'],
    ),
    setting(
      'models.autoRouting.quality',
      'Automatic routing quality policy',
      'Select the quality, balance, or cost priority for automatic model routing.',
      'models',
      { type: 'string', enum: ['quality-first', 'balanced', 'cost-first'] },
      'quality-first',
      ['platform', 'project', 'session'],
    ),
    setting(
      'models.autoRouting.maxLatencyMs',
      'Maximum routing latency (ms)',
      'Set zero for no maximum latency constraint.',
      'models',
      { type: 'integer', minimum: 0 },
      0,
      ['platform', 'project', 'session'],
    ),
    setting(
      'models.exploration.rate',
      'Model exploration rate',
      'Probability of exploring a less-observed eligible model.',
      'models',
      { type: 'number', minimum: 0, maximum: 1 },
      0.1,
      ['platform', 'project'],
    ),
    setting(
      'models.exploration.budgetUsdPerDay',
      'Daily model exploration budget (USD)',
      'Maximum daily spend on exploration picks.',
      'models',
      { type: 'number', minimum: 0 },
      1,
      ['platform', 'project'],
    ),
    setting(
      'models.budget.maxCostPerTaskUsd',
      'Maximum cost per task (USD)',
      'Maximum model spend allowed for a single task.',
      'models',
      { type: 'number', minimum: 0 },
      5,
      ['platform', 'project', 'session'],
    ),
    setting(
      'skills.catalog.maxEntries',
      'Maximum skill catalog entries',
      'Maximum number of eligible skills shown before search is needed.',
      'agents',
      { type: 'integer', minimum: 5 },
      40,
      ['platform', 'project'],
    ),
    setting(
      'skills.compatibilityScan.enabled',
      'Scan compatible skill directories',
      'Offer skills discovered in compatible agent-tool directories for trusted Projects.',
      'agents',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'skills.installLimits.archiveMiB',
      'Maximum skill archive size (MiB)',
      'Maximum compressed archive size accepted by the skill installer.',
      'plugins',
      { type: 'integer' },
      10,
      ['platform'],
    ),
    setting(
      'skills.installLimits.extractedMiB',
      'Maximum extracted skill size (MiB)',
      'Maximum total extracted size accepted by the skill installer.',
      'plugins',
      { type: 'integer' },
      25,
      ['platform'],
    ),
    setting(
      'skills.installLimits.maxFiles',
      'Maximum files in a skill archive',
      'Maximum number of files extracted by the skill installer.',
      'plugins',
      { type: 'integer' },
      1000,
      ['platform'],
    ),
    setting(
      'plugins.allowUnisolatedInFullAccess',
      'Allow unisolated plugins in Full access',
      'Permit plugin workers without OS isolation only for Projects in Full access mode.',
      'plugins',
      { type: 'boolean' },
      false,
      ['platform'],
    ),
    setting(
      'plugins.maxRestarts',
      'Maximum plugin worker restarts',
      'Maximum automatic restart attempts after a plugin worker crashes.',
      'plugins',
      { type: 'integer', minimum: 0, maximum: 20 },
      3,
      ['platform'],
    ),
    setting(
      'plugins.workerIdleStopMinutes',
      'Stop idle plugin workers after (minutes)',
      'Idle duration before a plugin worker is stopped; zero disables idle stopping.',
      'plugins',
      { type: 'integer', minimum: 0, maximum: 1440 },
      30,
      ['platform'],
    ),
    setting(
      'plugins.autoStart',
      'Start enabled plugins automatically',
      'Start enabled plugin workers when a Project is opened.',
      'plugins',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'mcp.autoConnect',
      'Connect enabled MCP servers automatically',
      'Automatically connect enabled platform and Project MCP connections.',
      'connections',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'mcp.reconnectBackoffSeconds',
      'MCP reconnection backoff (seconds)',
      'Delay before retrying a disconnected MCP connection.',
      'connections',
      { type: 'integer' },
      10,
      ['platform'],
    ),
    setting(
      'board.auditIntervalMinutes',
      'Board audit interval (minutes)',
      'Interval for the board-maintainer model pool to audit open threads and decisions.',
      'board',
      { type: 'integer', minimum: 1 },
      240,
      ['platform', 'project'],
    ),
    setting(
      'board.archiveAfterDays',
      'Archive resolved threads after (days)',
      'Age after which resolved threads are summarized and archived with their history retained.',
      'board',
      { type: 'integer', minimum: 1 },
      30,
      ['platform', 'project'],
    ),
    setting(
      'board.auditMinMessages',
      'Minimum thread messages for audit',
      'Only open threads with at least this many messages are sent for maintenance audit.',
      'board',
      { type: 'integer', minimum: 1 },
      5,
      ['platform', 'project'],
    ),
    setting(
      'board.maxSyncAttempts',
      'Maximum decision sync attempts',
      'Maximum automatic retries for a binding decision canon synchronization.',
      'board',
      { type: 'integer', minimum: 1 },
      5,
      ['platform', 'project'],
    ),
    setting(
      'board.allowPermanentDeletion',
      'Allow permanent board deletion',
      'Allow permanent thread deletion; otherwise board history may only be archived.',
      'board',
      { type: 'boolean' },
      false,
      ['platform', 'project'],
    ),
    setting(
      'board.maintenanceEnabled',
      'Enable board maintenance',
      'Enable scheduled board-maintainer audits and archive cleanup.',
      'board',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'search.vector.enabled',
      'Enable semantic vector search',
      'Enable the configured vector-store adapter for semantic retrieval.',
      'storage',
      { type: 'boolean' },
      false,
      ['platform', 'project'],
    ),
    setting(
      'backup.encryption.enabled',
      'Encrypt backups',
      'Encrypted by default; disabling is not recommended.',
      'storage',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'logs.retentionDays',
      'Log retention (days)',
      'Number of days to retain service logs.',
      'logs',
      { type: 'integer', minimum: 1 },
      30,
      ['platform'],
    ),
    setting(
      'engine.operationTimeoutSeconds',
      'Engine operation timeout (seconds)',
      'Maximum time an engine process may run before it is terminated.',
      'engine',
      { type: 'integer', minimum: 1, maximum: 86400 },
      1800,
      ['platform', 'project'],
    ),
    setting(
      'engine.autoDetectInstallations',
      'Automatically detect engine installations',
      'Detect engine executables from environment paths and common installation directories.',
      'engine',
      { type: 'boolean' },
      true,
      ['platform'],
    ),
    setting(
      'engine.postVersionMismatchToBoard',
      'Post engine version mismatches to the board',
      'Post one finding to the Engine board thread when the detected version changes out of compatibility.',
      'engine',
      { type: 'boolean' },
      true,
      ['project'],
    ),
    setting(
      'knowledge.vectorStore.kind',
      'Vector store kind',
      'Select Qdrant for semantic retrieval or none for lexical-only search.',
      'knowledge',
      { type: 'string', enum: ['none', 'qdrant'] },
      'none',
      ['platform', 'project'],
    ),
    setting(
      'knowledge.vectorStore.url',
      'Vector store URL',
      'Base URL for the Qdrant vector store.',
      'knowledge',
      { type: 'string', format: 'uri' },
      'http://127.0.0.1:6333',
      ['platform', 'project'],
    ),
    setting(
      'knowledge.vectorStore.apiKeyRef',
      'Vector store credential reference',
      'Optional reference to an encrypted credential in the platform credential store.',
      'knowledge',
      { type: 'string' },
      '',
      ['platform', 'project'],
    ),
    setting(
      'knowledge.vectorStore.collectionPrefix',
      'Vector store collection prefix',
      'Prefix used for Project-isolated Qdrant collections.',
      'knowledge',
      { type: 'string', minLength: 1 },
      'gamecrafter',
      ['platform', 'project'],
    ),
    setting(
      'knowledge.vectorStore.timeoutMs',
      'Vector store timeout (ms)',
      'Request timeout for the configured vector store.',
      'knowledge',
      { type: 'integer', minimum: 1 },
      5000,
      ['platform', 'project'],
    ),
    setting(
      'knowledge.embeddingBatchSize',
      'Embedding batch size',
      'Number of new chunks embedded in one provider request.',
      'knowledge',
      { type: 'integer', minimum: 1, maximum: 256 },
      32,
      ['platform', 'project'],
    ),
    setting(
      'knowledge.reconcileIntervalMinutes',
      'Knowledge reconcile interval (minutes)',
      'Periodic full reconciliation interval for Project knowledge indexes.',
      'knowledge',
      { type: 'integer', minimum: 1 },
      60,
      ['platform', 'project'],
    ),
    setting(
      'knowledge.indexCode',
      'Index Project code',
      'Include allowlisted source files under game/ in the knowledge index.',
      'knowledge',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'knowledge.indexBoard',
      'Index discussion board',
      'Include board threads and messages in the knowledge index.',
      'knowledge',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'knowledge.codeExtensions',
      'Indexed code extensions',
      'Allowlisted text/source extensions indexed from game/. Binary assets are never indexed as content.',
      'knowledge',
      { type: 'array', items: { type: 'string' }, uniqueItems: true },
      [
        'cs',
        'cpp',
        'h',
        'hpp',
        'gd',
        'tscn',
        'tres',
        'py',
        'ts',
        'js',
        'json',
        'ini',
        'cfg',
        'shader',
        'hlsl',
        'glsl',
        'usf',
        'ush',
        'md',
        'txt',
      ],
      ['platform', 'project'],
    ),
    setting(
      'assets.pollIntervalSeconds',
      'Asset job poll interval (seconds)',
      'Default delay between polling external asset generation jobs.',
      'assets',
      { type: 'integer', minimum: 2, maximum: 120 },
      5,
      ['platform', 'project'],
    ),
    setting(
      'assets.maxDownloadMb',
      'Maximum asset download size (MB)',
      'Reject provider output downloads larger than this limit.',
      'assets',
      { type: 'integer', minimum: 1, maximum: 4096 },
      200,
      ['platform', 'project'],
    ),
    setting(
      'assets.importDirectory',
      'Generated asset import directory',
      'Project-relative destination directory for approved generated assets.',
      'assets',
      { type: 'string', minLength: 1 },
      'game/assets/generated',
      ['platform', 'project'],
    ),
    setting(
      'assets.externalOpenCommand',
      'External asset authoring command',
      'Optional executable used to open assets in an authoring tool.',
      'assets',
      { type: 'string' },
      '',
      ['platform'],
    ),
    setting(
      'assets.previewCacheMb',
      'Asset preview cache size (MB)',
      'Maximum disk space used by disposable asset preview derivatives.',
      'assets',
      { type: 'integer', minimum: 1, maximum: 16384 },
      500,
      ['platform', 'project'],
    ),
    setting(
      'assets.requestTimeoutMs',
      'Asset provider request timeout (ms)',
      'Timeout applied to external asset provider API requests.',
      'assets',
      { type: 'integer', minimum: 1, maximum: 300000 },
      30000,
      ['platform', 'project'],
    ),
    setting(
      'backup.excludeGlobs',
      'Backup exclusion patterns',
      'Additional simple glob patterns excluded from Project backups.',
      'backup',
      { type: 'array', items: { type: 'string' }, uniqueItems: true },
      [],
      ['platform', 'project'],
    ),
    setting(
      'backup.includeAssetJobs',
      'Include generated asset jobs',
      'Include downloaded provider artifacts under .gamecrafter/asset-jobs in Project backups.',
      'backup',
      { type: 'boolean' },
      true,
      ['platform', 'project'],
    ),
    setting(
      'backup.compressionLevel',
      'Backup compression level',
      'Gzip compression level used for backup archives.',
      'backup',
      { type: 'integer', minimum: 0, maximum: 9 },
      6,
      ['platform'],
    ),
    setting(
      'backup.scryptLogN',
      'Backup secret KDF cost',
      'Scrypt logN used to protect recovery identities.',
      'backup',
      { type: 'integer', minimum: 14, maximum: 20 },
      15,
      ['platform'],
    ),
    setting(
      'backup.drillAfterBackup',
      'Drill after backup',
      'Decrypt and hash-check each new archive before retention runs.',
      'backup',
      { type: 'boolean' },
      true,
      ['platform'],
    ),
    setting(
      'backup.stagingDirectory',
      'Backup staging directory',
      'Optional directory for encrypted archive staging; empty uses the profile cache.',
      'backup',
      { type: 'string' },
      '',
      ['platform'],
    ),
    setting(
      'backup.maxArchiveMb',
      'Maximum archive size (MB)',
      'Zero means unlimited; otherwise fail before upload when the archive exceeds this size.',
      'backup',
      { type: 'integer', minimum: 0, maximum: 1048576 },
      0,
      ['platform'],
    ),
    setting(
      'dcc.searchPaths',
      'DCC executable search paths',
      'Additional directories to scan for DCC executables.',
      'dcc',
      { type: 'array', items: { type: 'string' } },
      [],
      ['platform'],
    ),
    setting(
      'dcc.operationTimeoutSeconds',
      'DCC operation timeout (seconds)',
      'Maximum time a headless DCC operation may run before termination.',
      'dcc',
      { type: 'integer', minimum: 1, maximum: 86400 },
      600,
      ['platform', 'project'],
    ),
    setting(
      'dcc.autoDetectInstallations',
      'Automatically detect DCC installations',
      'Detect DCC executables from PATH, common locations, and supported WSL interop paths.',
      'dcc',
      { type: 'boolean' },
      true,
      ['platform'],
    ),
    setting(
      'dcc.allowUnrestrictedScripts',
      'Allow unrestricted DCC scripts',
      'Allow DCC run-script calls containing subprocess or destructive filesystem operations.',
      'dcc',
      { type: 'boolean' },
      false,
      ['platform'],
    ),
    setting(
      'dcc.renderPreviewResolution',
      'DCC render preview resolution',
      'Resolution in pixels for generated DCC preview renders.',
      'dcc',
      { type: 'integer', minimum: 64, maximum: 4096 },
      512,
      ['platform', 'project'],
    ),
    setting(
      'coordination.autoIntegrate',
      'Automatic integration policy',
      'Control whether validated, conflict-free worktree changes are integrated automatically.',
      'coordination',
      { type: 'string', enum: ['never', 'when-validated', 'always'] },
      'when-validated',
      ['platform', 'project'],
    ),
    setting(
      'coordination.lockTimeoutSeconds',
      'Resource lock timeout (seconds)',
      'Time before an unrenewed resource lock expires.',
      'coordination',
      { type: 'integer', minimum: 1, maximum: 86400 },
      300,
      ['platform', 'project'],
    ),
    setting(
      'coordination.worktreeDirectory',
      'Worktree directory',
      'Project-relative directory used for isolated task worktrees.',
      'coordination',
      { type: 'string', minLength: 1 },
      '.gamecrafter/worktrees',
      ['platform', 'project'],
    ),
    setting(
      'coordination.impactConfidenceThreshold',
      'Impact confidence threshold',
      'Impact paths below this confidence need explicit validation.',
      'coordination',
      { type: 'number', minimum: 0, maximum: 1 },
      0.7,
      ['platform', 'project'],
    ),
    setting(
      'coordination.maxTranscriptTokens',
      'Optional agent context ceiling',
      'Zero uses selected-model capacity automatically. A positive value explicitly lowers the estimated input allowance, including messages and tool schemas; it cannot raise the model limit.',
      'coordination',
      { type: 'integer', minimum: 0 },
      0,
      ['platform', 'project'],
    ),
    setting(
      'coordination.defaultMaxTurns',
      'Default agent turn limit',
      'Default maximum model turns for roles without max-turns.',
      'coordination',
      { type: 'integer', minimum: 1, maximum: 1000 },
      60,
      ['platform', 'project'],
    ),
    setting(
      'updates.checkOnStart',
      'Check for updates on startup',
      'Check the stable release channel after the Control Room starts.',
      'updates',
      { type: 'boolean' },
      false,
      ['platform'],
    ),
    setting(
      'updates.releasesUrl',
      'Stable releases URL',
      'GitHub latest-release API URL or a direct gamecrafter-release.json URL.',
      'updates',
      { type: 'string', format: 'uri', minLength: 1 },
      'https://api.github.com/repos/scarecr0w12/GameCrafter/releases/latest',
      ['platform'],
    ),
    setting(
      'updates.autoDownload',
      'Download updates automatically',
      'Download a compatible release after checking; installation always remains user-controlled.',
      'updates',
      { type: 'boolean' },
      false,
      ['platform'],
    ),
    setting(
      'updates.checkIntervalHours',
      'Update check interval (hours)',
      'Interval between background stable-channel checks.',
      'updates',
      { type: 'integer', minimum: 1, maximum: 720 },
      24,
      ['platform'],
    ),
    setting(
      'updates.signingPublicKey',
      'Release signing public key',
      'Ed25519 public key used to verify the detached release checksum signature.',
      'updates',
      { type: 'string' },
      '',
      ['platform'],
    ),
  ];

  return { groups, definitions };
}

function setting(
  key: string,
  title: string,
  description: string,
  group: string,
  schema: Record<string, unknown>,
  defaultValue: unknown,
  scopes: SettingDefinition['scopes'],
): SettingDefinition {
  return {
    key,
    title,
    description,
    group,
    schema,
    default: defaultValue,
    scopes,
    source: 'builtin',
  };
}
